In [2]:
import requests
teams = requests.get("https://api-web.nhle.com/v1/standings/2026-04-17")

In [5]:
teams

In [10]:
data: dict = teams.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['wildCardIndicator', 'standingsDateTimeUtc', 'standings'])

In [7]:
type(data)

dict

In [8]:
data

{'wildCardIndicator': True,
 'standingsDateTimeUtc': '2026-09-20T15:35:30Z',
 'standings': [{'clinchIndicator': 'p',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 1,
   'divisionName': 'Central',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 99,
   'goalDifferentialPctg': 1.207317,
   'goalAgainst': 203,
   'goalFor': 302,
   'goalsForPctg': 3.682927,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 49,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 157,
   'homeLosses': 9,
   'homeOtLosses': 6,
   'homePoints': 58,
   'homeRegulationPlusOtWins': 25,
   'homeRegulationWins': 25,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 14,
   'l10GoalsAgainst': 20,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 3,
   'leagueL10Sequence': 4,
   'leagueRoadSequence': 1,
   'leagueSequence': 1,
   'losses': 16,
   'otLosses': 11,
   'placeName': {'default': 'Colorado'},
   'pointPctg': 0.737805,
   'points': 121,
   'regulationPlusOtWinPctg': 0.621951,
   'regulationPlusOtWins': 51,
   'regulationWinPctg': 0.585366,
   'regulationWins': 48,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 50,
   'roadGoalsAgainst': 95,
   'roadGoalsFor': 145,
   'roadLosses': 7,
   'roadOtLosses': 5,
   'roadPoints': 63,
   'roadRegulationPlusOtWins': 26,
   'roadRegulationWins': 23,
   'roadTies': 0,
   'roadWins': 29,
   'seasonId': 20252026,
   'shootoutLosses': 6,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 3,
   'teamName': {'default': 'Colorado Avalanche',
    'fr': 'Avalanche du Colorado'},
   'teamCommonName': {'default': 'Avalanche'},
   'teamAbbrev': {'default': 'COL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
   'ties': 0,
   'waiversSequence': 32,
   'wildcardSequence': 0,
   'winPctg': 0.670732,
   'wins': 55},
  {'clinchIndicator': 'z',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 3,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'M',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 2,
   'divisionName': 'Metropolitan',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 56,
   'goalDifferentialPctg': 0.682927,
   'goalAgainst': 240,
   'goalFor': 296,
   'goalsForPctg': 3.609756,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 35,
   'homeGoalsAgainst': 126,
   'homeGoalsFor': 161,
   'homeLosses': 10,
   'homeOtLosses': 2,
   'homePoints': 60,
   'homeRegulationPlusOtWins': 27,
   'homeRegulationWins': 20,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 12,
   'l10GoalsAgainst': 27,
   'l10GoalsFor': 39,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 7,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 1,
   'leagueL10Sequence': 3,
   'leagueRoadSequence': 5,
   'leagueSequence': 2,
   'losses': 22,
   'otLosses': 7,
   'placeName': {'default': 'Carolina', 'fr': 'Caroline'},
   'pointPctg': 0.689024,
   'points': 113,
   'regulationPlusOtWinPctg': 0.585366,
   'regulationPlusOtWins': 48,
   'regulationWinPctg': 0.47561,
   'regulationWins': 39,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 21,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 135,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 21,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 5,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Carolina Hurricanes',
    'fr': 'Hurricanes de la Caroline'},
   'teamCommonName': {'default': 'Hurricanes'},
   'teamAbbrev': {'default': 'CAR'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
   'ties': 0,
   'waiversSequence': 31,
   'wildcardSequence': 0,
   'winPctg': 0.646341,
   'wins': 53},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 2,
   'divisionName': 'Central',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 53,
   'goalDifferentialPctg': 0.646341,
   'goalAgainst': 226,
   'goalFor': 279,
   'goalsForPctg': 3.402439,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 23,
   'homeGoalsAgainst': 112,
   'homeGoalsFor': 135,
   'homeLosses': 11,
   'homeOtLosses': 4,
   'homePoints': 56,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 28,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 5,
   'leagueL10Sequence': 5,
   'leagueRoadSequence': 2,
   'leagueSequence': 3,
   'losses': 20,
   'otLosses': 12,
   'placeName': {'default': 'Dallas'},
   'pointPctg': 0.682927,
   'points': 112,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 30,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 144,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 6,
   'streakCode': 'W',
   'streakCount': 5,
   'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'},
   'teamCommonName': {'default': 'Stars'},
   'teamAbbrev': {'default': 'DAL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
   'ties': 0,
   'waiversSequence': 30,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'y',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 6,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 3,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 3,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 47,
   'goalDifferentialPctg': 0.573171,
   'goalAgainst': 241,
   'goalFor': 288,
   'goalsForPctg': 3.512195,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 30,
   'homeGoalsAgainst': 119,
   'homeGoalsFor': 149,
   'homeLosses': 10,
   'homeOtLosses': 5,
   'homePoints': 57,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 22,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 34,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 4,
   'leagueL10Sequence': 12,
   'leagueRoadSequence': 6,
   'leagueSequence': 4,
   'losses': 23,
   'otLosses': 9,
   'placeName': {'default': 'Buffalo'},
   'pointPctg': 0.664634,
   'points': 109,
   'regulationPlusOtWinPctg': 0.54878,
   'regulationPlusOtWins': 45,
   'regulationWinPctg': 0.512195,
   'regulationWins': 42,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 122,
   'roadGoalsFor': 139,
   'roadLosses': 13,
   'roadOtLosses': 4,
   'roadPoints': 52,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 20,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 1,
   'shootoutWins': 5,
   'streakCode': 'OT',
   'streakCount': 1,
   'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'},
   'teamCommonName': {'default': 'Sabres'},
   'teamAbbrev': {'default': 'BUF'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
   'ties': 0,
   'waiversSequence': 29,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 5,
   'conferenceL10Sequence': 12,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 6,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 59,
   'goalDifferentialPctg': 0.719512,
   'goalAgainst': 231,
   'goalFor': 290,
   'goalsForPctg': 3.536585,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 22,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 137,
   'homeLosses': 14,
   'homeOtLosses': 1,
   'homePoints': 53,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': -4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 26,
   'l10Losses': 5,
   'l10OtLosses': 0,
   'l10Points': 10,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 8,
   'leagueL10Sequence': 21,
   'leagueRoadSequence': 4,
   'leagueSequence': 5,
   'losses': 26,
   'otLosses': 6,
   'placeName': {'default': 'Tampa Bay'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.560976,
   'regulationPlusOtWins': 46,
   'regulationWinPctg': 0.487805,
   'regulationWins': 40,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 37,
   'roadGoalsAgainst': 116,
   'roadGoalsFor': 153,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 21,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 2,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Tampa Bay Lightning',
    'fr': 'Lightning de Tampa Bay'},
   'teamCommonName': {'default': 'Lightning'},
   'teamAbbrev': {'default': 'TBL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
   'ties': 0,
   'waiversSequence': 28,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 7,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 4,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 5,
   'divisionL10Sequence': 1,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 1,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 27,
   'goalDifferentialPctg': 0.329268,
   'goalAgainst': 256,
   'goalFor': 283,
   'goalsForPctg': 3.45122,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 10,
   'homeGoalsAgainst': 127,
   'homeGoalsFor': 137,
   'homeLosses': 15,
   'homeOtLosses': 2,
   'homePoints': 50,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 17,
   'homeTies': 0,
   'homeWins': 24,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 24,
   'l10GoalsFor': 28,
   'l10Losses': 3,
   'l10OtLosses': 0,
   'l10Points': 14,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 12,
   'leagueL10Sequence': 7,
   'leagueRoadSequence': 3,
   'leagueSequence': 6,
   'losses': 24,
   'otLosses': 10,
   'placeName': {'default': 'Montréal'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.414634,
   'regulationWins': 34,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 129,
   'roadGoalsFor': 146,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Montréal Canadiens',
    'fr': 'Canadiens de Montréal'},
   'teamCommonName': {'default': 'Canadiens'},
   'teamAbbrev': {'default': 'MTL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
   'ties': 0,
   'waiversSequence': 27,
   'wildcardSequence': 0,
   'winPctg': 0.585366,
   'wins': 48},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 7,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 4,
   'divisionName': 'Central',
   'divisionRoadSequence': 3,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 240,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 15,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 130,
   'homeLosses': 10,
   'homeOtLosses': 8,
   'homePoints': 54,
   'homeRegulationPlusOtWins': 19,
   'homeRegulationWins': 14,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 32,
   'l10GoalsFor': 36,
   'l10Losses': 4,
   'l10OtLosses': 0,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 7,
   'leagueL10Sequence': 14,
   'leagueRoadSequence': 9,
   'leagueSequence': 7,
   'losses': 24,
   'otLosses': 12,
   'placeName': {'default': 'Minnesota'},
   'pointPctg': 0.634146,
   'points': 104,
   'regulationPlusOtWinPctg': 0.512195,
   'regulationPlusOtWins': 42,
   'regulationWinPctg': 0.378049,
   'regulationWins': 31,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 125,
   'roadGoalsFor': 142,
   'roadLosses': 14,
   'roadOtLosses': 4,
   'roadPoints': 50,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 23,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'},
   'teamCommonName': {'default': 'Wild'},
   'teamAbbrev': {'default': 'MIN'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
   'ties': 0,
   'waiversSequence': 26,
   'wildcardSequence': 0,
   'winPctg': 0.560976,
   'wins': 46},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 8,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 13,
   'conferenceSequence': 5,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 4,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 6,
   'divisionSequence': 4,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 22,
   'goalDifferentialPctg': 0.268293,
   'goalAgainst': 250,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 40,
   'homeGoalsAgainst': 105,
   'homeGoalsFor': 145,
   'homeLosses': 11,
   'homeOtLosses': 1,
   'homePoints': 59,
   'homeRegulationPlusOtWins': 28,
   'homeRegulationWins': 23,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 32,
   'l10Losses': 3,
   'l10OtLosses': 2,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 4,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 2,
   'leagueL10Sequence': 16,
   'leagueRoadSequence': 21,
   'leagueSequence': 8,
   'losses': 27,
   'otLosses': 10,
   'placeName': {'default': 'Boston'},
   'pointPctg': 0.609756,
   'points': 100,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.402439,
   'regulationWins': 33,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': -18,
   'roadGoalsAgainst': 145,
   'roadGoalsFor': 127,
   'roadLosses': 16,
   'roadOtLosses': 9,
   'roadPoints': 41,
   'roadRegulationPlusOtWins': 13,
   'roadRegulationWins': 10,
   'roadTies': 0,
   'roadWins': 16,
   'seasonId': 20252026,
   'shootoutLosses': 3,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 2,
   'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'},
   'teamCommonName': {'default': 'Bruins'},
   'teamAbbrev': {'default': 'BOS'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026',
   'ties': 0,
   'waiversSequence': 25,
   'wildcardSequence': 1,
   'winPctg': 0.54878,
   'wins': 45},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 6,
   'conferenceL10Sequence': 5,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 7,
   'conferenceSequence': 6,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 4,
   'divisionL10Sequence': 2,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 4,
   'divisionSequence': 5,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 246,
   'goalFor': 278,
   'goalsForPctg': 3.390244,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 31,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 139,
   'homeLosses': 12,
   'homeOtLosses': 6,
   'homePoints': 52,
   'homeRegulationPlusOtWins': 21,
   'homeRegulationWins': 21,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 10,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 36,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 9,
   'leagueL10Sequence': 10,
   'leagueRoadSequence': 11,
   'leagueSequence': 9,
   'losses': 27,
   'otLosses': 11,
   'placeName': {'default': 'Ottawa'},
   'pointPctg': 0.603659,
   'points': 99,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 1,
   'roadGoalsAgainst': 138,
   'roadGoalsFor': 139,
   'roadLosses': 15,
   'roadOtLosses': 5,
   'roadPoints': 47,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 17,

In [9]:
data['standings']

[{'clinchIndicator': 'p',
  'conferenceAbbrev': 'W',
  'conferenceHomeSequence': 1,
  'conferenceL10Sequence': 2,
  'conferenceName': 'Western',
  'conferenceRoadSequence': 1,
  'conferenceSequence': 1,
  'date': '2026-04-17',
  'divisionAbbrev': 'C',
  'divisionHomeSequence': 1,
  'divisionL10Sequence': 1,
  'divisionName': 'Central',
  'divisionRoadSequence': 1,
  'divisionSequence': 1,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 99,
  'goalDifferentialPctg': 1.207317,
  'goalAgainst': 203,
  'goalFor': 302,
  'goalsForPctg': 3.682927,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 49,
  'homeGoalsAgainst': 108,
  'homeGoalsFor': 157,
  'homeLosses': 9,
  'homeOtLosses': 6,
  'homePoints': 58,
  'homeRegulationPlusOtWins': 25,
  'homeRegulationWins': 25,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 14,
  'l10GoalsAgainst': 20,
  'l10GoalsFor': 34,
  'l10Losses': 2,
  'l10OtLosses': 1,
  'l10Points': 15,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 3,
  'leagueL10Sequence': 4,
  'leagueRoadSequence': 1,
  'leagueSequence': 1,
  'losses': 16,
  'otLosses': 11,
  'placeName': {'default': 'Colorado'},
  'pointPctg': 0.737805,
  'points': 121,
  'regulationPlusOtWinPctg': 0.621951,
  'regulationPlusOtWins': 51,
  'regulationWinPctg': 0.585366,
  'regulationWins': 48,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 50,
  'roadGoalsAgainst': 95,
  'roadGoalsFor': 145,
  'roadLosses': 7,
  'roadOtLosses': 5,
  'roadPoints': 63,
  'roadRegulationPlusOtWins': 26,
  'roadRegulationWins': 23,
  'roadTies': 0,
  'roadWins': 29,
  'seasonId': 20252026,
  'shootoutLosses': 6,
  'shootoutWins': 4,
  'streakCode': 'W',
  'streakCount': 3,
  'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'},
  'teamCommonName': {'default': 'Avalanche'},
  'teamAbbrev': {'default': 'COL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
  'ties': 0,
  'waiversSequence': 32,
  'wildcardSequence': 0,
  'winPctg': 0.670732,
  'wins': 55},
 {'clinchIndicator': 'z',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 1,
  'conferenceL10Sequence': 2,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 3,
  'conferenceSequence': 1,
  'date': '2026-04-17',
  'divisionAbbrev': 'M',
  'divisionHomeSequence': 1,
  'divisionL10Sequence': 2,
  'divisionName': 'Metropolitan',
  'divisionRoadSequence': 1,
  'divisionSequence': 1,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 56,
  'goalDifferentialPctg': 0.682927,
  'goalAgainst': 240,
  'goalFor': 296,
  'goalsForPctg': 3.609756,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 35,
  'homeGoalsAgainst': 126,
  'homeGoalsFor': 161,
  'homeLosses': 10,
  'homeOtLosses': 2,
  'homePoints': 60,
  'homeRegulationPlusOtWins': 27,
  'homeRegulationWins': 20,
  'homeTies': 0,
  'homeWins': 29,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 12,
  'l10GoalsAgainst': 27,
  'l10GoalsFor': 39,
  'l10Losses': 2,
  'l10OtLosses': 1,
  'l10Points': 15,
  'l10RegulationPlusOtWins': 7,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 1,
  'leagueL10Sequence': 3,
  'leagueRoadSequence': 5,
  'leagueSequence': 2,
  'losses': 22,
  'otLosses': 7,
  'placeName': {'default': 'Carolina', 'fr': 'Caroline'},
  'pointPctg': 0.689024,
  'points': 113,
  'regulationPlusOtWinPctg': 0.585366,
  'regulationPlusOtWins': 48,
  'regulationWinPctg': 0.47561,
  'regulationWins': 39,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 21,
  'roadGoalsAgainst': 114,
  'roadGoalsFor': 135,
  'roadLosses': 12,
  'roadOtLosses': 5,
  'roadPoints': 53,
  'roadRegulationPlusOtWins': 21,
  'roadRegulationWins': 19,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 4,
  'shootoutWins': 5,
  'streakCode': 'W',
  'streakCount': 1,
  'teamName': {'default': 'Carolina Hurricanes',
   'fr': 'Hurricanes de la Caroline'},
  'teamCommonName': {'default': 'Hurricanes'},
  'teamAbbrev': {'default': 'CAR'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
  'ties': 0,
  'waiversSequence': 31,
  'wildcardSequence': 0,
  'winPctg': 0.646341,
  'wins': 53},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'W',
  'conferenceHomeSequence': 2,
  'conferenceL10Sequence': 3,
  'conferenceName': 'Western',
  'conferenceRoadSequence': 2,
  'conferenceSequence': 2,
  'date': '2026-04-17',
  'divisionAbbrev': 'C',
  'divisionHomeSequence': 2,
  'divisionL10Sequence': 2,
  'divisionName': 'Central',
  'divisionRoadSequence': 2,
  'divisionSequence': 2,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 53,
  'goalDifferentialPctg': 0.646341,
  'goalAgainst': 226,
  'goalFor': 279,
  'goalsForPctg': 3.402439,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 23,
  'homeGoalsAgainst': 112,
  'homeGoalsFor': 135,
  'homeLosses': 11,
  'homeOtLosses': 4,
  'homePoints': 56,
  'homeRegulationPlusOtWins': 24,
  'homeRegulationWins': 19,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 6,
  'l10GoalsAgainst': 28,
  'l10GoalsFor': 34,
  'l10Losses': 2,
  'l10OtLosses': 1,
  'l10Points': 15,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 5,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 5,
  'leagueL10Sequence': 5,
  'leagueRoadSequence': 2,
  'leagueSequence': 3,
  'losses': 20,
  'otLosses': 12,
  'placeName': {'default': 'Dallas'},
  'pointPctg': 0.682927,
  'points': 112,
  'regulationPlusOtWinPctg': 0.536585,
  'regulationPlusOtWins': 44,
  'regulationWinPctg': 0.463415,
  'regulationWins': 38,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 30,
  'roadGoalsAgainst': 114,
  'roadGoalsFor': 144,
  'roadLosses': 9,
  'roadOtLosses': 8,
  'roadPoints': 56,
  'roadRegulationPlusOtWins': 20,
  'roadRegulationWins': 19,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 4,
  'shootoutWins': 6,
  'streakCode': 'W',
  'streakCount': 5,
  'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'},
  'teamCommonName': {'default': 'Stars'},
  'teamAbbrev': {'default': 'DAL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
  'ties': 0,
  'waiversSequence': 30,
  'wildcardSequence': 0,
  'winPctg': 0.609756,
  'wins': 50},
 {'clinchIndicator': 'y',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 3,
  'conferenceL10Sequence': 6,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 4,
  'conferenceSequence': 2,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 2,
  'divisionL10Sequence': 3,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 3,
  'divisionSequence': 1,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 47,
  'goalDifferentialPctg': 0.573171,
  'goalAgainst': 241,
  'goalFor': 288,
  'goalsForPctg': 3.512195,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 30,
  'homeGoalsAgainst': 119,
  'homeGoalsFor': 149,
  'homeLosses': 10,
  'homeOtLosses': 5,
  'homePoints': 57,
  'homeRegulationPlusOtWins': 22,
  'homeRegulationWins': 22,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 4,
  'l10GoalsAgainst': 30,
  'l10GoalsFor': 34,
  'l10Losses': 3,
  'l10OtLosses': 1,
  'l10Points': 13,
  'l10RegulationPlusOtWins': 5,
  'l10RegulationWins': 5,
  'l10Ties': 0,
  'l10Wins': 6,
  'leagueHomeSequence': 4,
  'leagueL10Sequence': 12,
  'leagueRoadSequence': 6,
  'leagueSequence': 4,
  'losses': 23,
  'otLosses': 9,
  'placeName': {'default': 'Buffalo'},
  'pointPctg': 0.664634,
  'points': 109,
  'regulationPlusOtWinPctg': 0.54878,
  'regulationPlusOtWins': 45,
  'regulationWinPctg': 0.512195,
  'regulationWins': 42,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 17,
  'roadGoalsAgainst': 122,
  'roadGoalsFor': 139,
  'roadLosses': 13,
  'roadOtLosses': 4,
  'roadPoints': 52,
  'roadRegulationPlusOtWins': 23,
  'roadRegulationWins': 20,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 1,
  'shootoutWins': 5,
  'streakCode': 'OT',
  'streakCount': 1,
  'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'},
  'teamCommonName': {'default': 'Sabres'},
  'teamAbbrev': {'default': 'BUF'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
  'ties': 0,
  'waiversSequence': 29,
  'wildcardSequence': 0,
  'winPctg': 0.609756,
  'wins': 50},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 5,
  'conferenceL10Sequence': 12,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 2,
  'conferenceSequence': 3,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 3,
  'divisionL10Sequence': 6,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 2,
  'divisionSequence': 2,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 59,
  'goalDifferentialPctg': 0.719512,
  'goalAgainst': 231,
  'goalFor': 290,
  'goalsForPctg': 3.536585,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 22,
  'homeGoalsAgainst': 115,
  'homeGoalsFor': 137,
  'homeLosses': 14,
  'homeOtLosses': 1,
  'homePoints': 53,
  'homeRegulationPlusOtWins': 24,
  'homeRegulationWins': 19,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': -4,
  'l10GoalsAgainst': 30,
  'l10GoalsFor': 26,
  'l10Losses': 5,
  'l10OtLosses': 0,
  'l10Points': 10,
  'l10RegulationPlusOtWins': 5,
  'l10RegulationWins': 4,
  'l10Ties': 0,
  'l10Wins': 5,
  'leagueHomeSequence': 8,
  'leagueL10Sequence': 21,
  'leagueRoadSequence': 4,
  'leagueSequence': 5,
  'losses': 26,
  'otLosses': 6,
  'placeName': {'default': 'Tampa Bay'},
  'pointPctg': 0.646341,
  'points': 106,
  'regulationPlusOtWinPctg': 0.560976,
  'regulationPlusOtWins': 46,
  'regulationWinPctg': 0.487805,
  'regulationWins': 40,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 37,
  'roadGoalsAgainst': 116,
  'roadGoalsFor': 153,
  'roadLosses': 12,
  'roadOtLosses': 5,
  'roadPoints': 53,
  'roadRegulationPlusOtWins': 22,
  'roadRegulationWins': 21,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 2,
  'shootoutWins': 4,
  'streakCode': 'L',
  'streakCount': 1,
  'teamName': {'default': 'Tampa Bay Lightning',
   'fr': 'Lightning de Tampa Bay'},
  'teamCommonName': {'default': 'Lightning'},
  'teamAbbrev': {'default': 'TBL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
  'ties': 0,
  'waiversSequence': 28,
  'wildcardSequence': 0,
  'winPctg': 0.609756,
  'wins': 50},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 7,
  'conferenceL10Sequence': 3,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 1,
  'conferenceSequence': 4,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 5,
  'divisionL10Sequence': 1,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 1,
  'divisionSequence': 3,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 27,
  'goalDifferentialPctg': 0.329268,
  'goalAgainst': 256,
  'goalFor': 283,
  'goalsForPctg': 3.45122,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 10,
  'homeGoalsAgainst': 127,
  'homeGoalsFor': 137,
  'homeLosses': 15,
  'homeOtLosses': 2,
  'homePoints': 50,
  'homeRegulationPlusOtWins': 22,
  'homeRegulationWins': 17,
  'homeTies': 0,
  'homeWins': 24,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 4,
  'l10GoalsAgainst': 24,
  'l10GoalsFor': 28,
  'l10Losses': 3,
  'l10OtLosses': 0,
  'l10Points': 14,
  'l10RegulationPlusOtWins': 5,
  'l10RegulationWins': 5,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 12,
  'leagueL10Sequence': 7,
  'leagueRoadSequence': 3,
  'leagueSequence': 6,
  'losses': 24,
  'otLosses': 10,
  'placeName': {'default': 'Montréal'},
  'pointPctg': 0.646341,
  'points': 106,
  'regulationPlusOtWinPctg': 0.536585,
  'regulationPlusOtWins': 44,
  'regulationWinPctg': 0.414634,
  'regulationWins': 34,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 17,
  'roadGoalsAgainst': 129,
  'roadGoalsFor': 146,
  'roadLosses': 9,
  'roadOtLosses': 8,
  'roadPoints': 56,
  'roadRegulationPlusOtWins': 22,
  'roadRegulationWins': 17,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 5,
  'shootoutWins': 4,
  'streakCode': 'L',
  'streakCount': 1,
  'teamName': {'default': 'Montréal Canadiens', 'fr': 'Canadiens de Montréal'},
  'teamCommonName': {'default': 'Canadiens'},
  'teamAbbrev': {'default': 'MTL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
  'ties': 0,
  'waiversSequence': 27,
  'wildcardSequence': 0,
  'winPctg': 0.585366,
  'wins': 48},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'W',
  'conferenceHomeSequence': 3,
  'conferenceL10Sequence': 7,
  'conferenceName': 'Western',
  'conferenceRoadSequence': 4,
  'conferenceSequence': 3,
  'date': '2026-04-17',
  'divisionAbbrev': 'C',
  'divisionHomeSequence': 3,
  'divisionL10Sequence': 4,
  'divisionName': 'Central',
  'divisionRoadSequence': 3,
  'divisionSequence': 3,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 32,
  'goalDifferentialPctg': 0.390244,
  'goalAgainst': 240,
  'goalFor': 272,
  'goalsForPctg': 3.317073,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 15,
  'homeGoalsAgainst': 115,
  'homeGoalsFor': 130,
  'homeLosses': 10,
  'homeOtLosses': 8,
  'homePoints': 54,
  'homeRegulationPlusOtWins': 19,
  'homeRegulationWins': 14,
  'homeTies': 0,
  'homeWins': 23,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 4,
  'l10GoalsAgainst': 32,
  'l10GoalsFor': 36,
  'l10Losses': 4,
  'l10OtLosses': 0,
  'l10Points': 12,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 6,
  'leagueHomeSequence': 7,
  'leagueL10Sequence': 14,
  'leagueRoadSequence': 9,
  'leagueSequence': 7,
  'losses': 24,
  'otLosses': 12,
  'placeName': {'default': 'Minnesota'},
  'pointPctg': 0.634146,
  'points': 104,
  'regulationPlusOtWinPctg': 0.512195,
  'regulationPlusOtWins': 42,
  'regulationWinPctg': 0.378049,
  'regulationWins': 31,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 17,
  'roadGoalsAgainst': 125,
  'roadGoalsFor': 142,
  'roadLosses': 14,
  'roadOtLosses': 4,
  'roadPoints': 50,
  'roadRegulationPlusOtWins': 23,
  'roadRegulationWins': 17,
  'roadTies': 0,
  'roadWins': 23,
  'seasonId': 20252026,
  'shootoutLosses': 5,
  'shootoutWins': 4,
  'streakCode': 'W',
  'streakCount': 1,
  'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'},
  'teamCommonName': {'default': 'Wild'},
  'teamAbbrev': {'default': 'MIN'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
  'ties': 0,
  'waiversSequence': 26,
  'wildcardSequence': 0,
  'winPctg': 0.560976,
  'wins': 46},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 2,
  'conferenceL10Sequence': 8,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 13,
  'conferenceSequence': 5,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 1,
  'divisionL10Sequence': 4,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 6,
  'divisionSequence': 4,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 22,
  'goalDifferentialPctg': 0.268293,
  'goalAgainst': 250,
  'goalFor': 272,
  'goalsForPctg': 3.317073,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 40,
  'homeGoalsAgainst': 105,
  'homeGoalsFor': 145,
  'homeLosses': 11,
  'homeOtLosses': 1,
  'homePoints': 59,
  'homeRegulationPlusOtWins': 28,
  'homeRegulationWins': 23,
  'homeTies': 0,
  'homeWins': 29,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 6,
  'l10GoalsAgainst': 26,
  'l10GoalsFor': 32,
  'l10Losses': 3,
  'l10OtLosses': 2,
  'l10Points': 12,
  'l10RegulationPlusOtWins': 4,
  'l10RegulationWins': 4,
  'l10Ties': 0,
  'l10Wins': 5,
  'leagueHomeSequence': 2,
  'leagueL10Sequence': 16,
  'leagueRoadSequence': 21,
  'leagueSequence': 8,
  'losses': 27,
  'otLosses': 10,
  'placeName': {'default': 'Boston'},
  'pointPctg': 0.609756,
  'points': 100,
  'regulationPlusOtWinPctg': 0.5,
  'regulationPlusOtWins': 41,
  'regulationWinPctg': 0.402439,
  'regulationWins': 33,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': -18,
  'roadGoalsAgainst': 145,
  'roadGoalsFor': 127,
  'roadLosses': 16,
  'roadOtLosses': 9,
  'roadPoints': 41,
  'roadRegulationPlusOtWins': 13,
  'roadRegulationWins': 10,
  'roadTies': 0,
  'roadWins': 16,
  'seasonId': 20252026,
  'shootoutLosses': 3,
  'shootoutWins': 4,
  'streakCode': 'W',
  'streakCount': 2,
  'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'},
  'teamCommonName': {'default': 'Bruins'},
  'teamAbbrev': {'default': 'BOS'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026',
  'ties': 0,
  'waiversSequence': 25,
  'wildcardSequence': 1,
  'winPctg': 0.54878,
  'wins': 45},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 6,
  'conferenceL10Sequence': 5,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 7,
  'conferenceSequence': 6,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 4,
  'divisionL10Sequence': 2,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 4,
  'divisionSequence': 5,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 32,
  'goalDifferentialPctg': 0.390244,
  'goalAgainst': 246,
  'goalFor': 278,
  'goalsForPctg': 3.390244,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 31,
  'homeGoalsAgainst': 108,
  'homeGoalsFor': 139,
  'homeLosses': 12,
  'homeOtLosses': 6,
  'homePoints': 52,
  'homeRegulationPlusOtWins': 21,
  'homeRegulationWins': 21,
  'homeTies': 0,
  'homeWins': 23,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 10,
  'l10GoalsAgainst': 26,
  'l10GoalsFor': 36,
  'l10Losses': 3,
  'l10OtLosses': 1,
  'l10Points': 13,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 6,
  'leagueHomeSequence': 9,
  'leagueL10Sequence': 10,
  'leagueRoadSequence': 11,
  'leagueSequence': 9,
  'losses': 27,
  'otLosses': 11,
  'placeName': {'default': 'Ottawa'},
  'pointPctg': 0.603659,
  'points': 99,
  'regulationPlusOtWinPctg': 0.5,
  'regulationPlusOtWins': 41,
  'regulationWinPctg': 0.463415,
  'regulationWins': 38,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 1,
  'roadGoalsAgainst': 138,
  'roadGoalsFor': 139,
  'roadLosses': 15,
  'roadOtLosses': 5,
  'roadPoints': 47,
  'roadRegulationPlusOtWins': 20,
  'roadRegulationWins': 17,
  'roadTies': 0,
  'roadWins': 21,
  'seasonId': 20252026,
  'shootoutLosses': 1,
  'shootoutWins': 3,
  'streakCode': 'W',
  'streakCount': 1,
  'teamName': {'default': 'Ottawa Senators', 'fr': "Sénateurs d'Ottawa"},
  'teamCommonName': {'default': 'Senators', 'fr': 'Sénateurs'},
  'teamAbbrev': {'default': 'OTT'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg',
  'ties': 0,
  'waiversSequence': 24,
  'wildcardSequence': 2,
  'winPctg': 0.536585,
  'wins': 44},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 10,
  'conferenceL10Sequence': 11,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 5,
  'conferenceSequence': 7,
  'date': '2026-04-17',
  'divisionAbbrev': 'M',

In [18]:
records = []

for team_id, team in enumerate(data['standings'], start=1):
    team_abbrev = team['teamAbbrev']['default']
    team_name = team['teamName']['default']
    conf_name = team['conferenceName']
    div_name = team['divisionName']
    logo_url = team['teamLogo']

    records.append(dict(
        team_id=team_id,
        team_abbrev=team_abbrev,
        team_name=team_name,
        conference_name=conf_name,
        division_name=div_name,
        logo_url=logo_url
    ))

print(f'Total teams: {len(records)}')
records

Total teams: 32

[{'team_id': 1,
  'team_abbrev': 'COL',
  'team_name': 'Colorado Avalanche',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg'},
 {'team_id': 2,
  'team_abbrev': 'CAR',
  'team_name': 'Carolina Hurricanes',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg'},
 {'team_id': 3,
  'team_abbrev': 'DAL',
  'team_name': 'Dallas Stars',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg'},
 {'team_id': 4,
  'team_abbrev': 'BUF',
  'team_name': 'Buffalo Sabres',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg'},
 {'team_id': 5,
  'team_abbrev': 'TBL',
  'team_name': 'Tampa Bay Lightning',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg'},
 {'team_id': 6,
  'team_abbrev': 'MTL',
  'team_name': 'Montréal Canadiens',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg'},
 {'team_id': 7,
  'team_abbrev': 'MIN',
  'team_name': 'Minnesota Wild',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg'},
 {'team_id': 8,
  'team_abbrev': 'BOS',
  'team_name': 'Boston Bruins',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026'},
 {'team_id': 9,
  'team_abbrev': 'OTT',
  'team_name': 'Ottawa Senators',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg'},
 {'team_id': 10,
  'team_abbrev': 'PIT',
  'team_name': 'Pittsburgh Penguins',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/PIT_light.svg'},
 {'team_id': 11,
  'team_abbrev': 'PHI',
  'team_name': 'Philadelphia Flyers',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/PHI_light.svg'},
 {'team_id': 12,
  'team_abbrev': 'WSH',
  'team_name': 'Washington Capitals',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/WSH_secondary_light.svg'},
 {'team_id': 13,
  'team_abbrev': 'VGK',
  'team_name': 'Vegas Golden Knights',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/VGK_light.svg'},
 {'team_id': 14,
  'team_abbrev': 'EDM',
  'team_name': 'Edmonton Oilers',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/EDM_light.svg'},
 {'team_id': 15,
  'team_abbrev': 'UTA',
  'team_name': 'Utah Mammoth',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/UTA_light.svg?season=20252026'},
 {'team_id': 16,
  'team_abbrev': 'DET',
  'team_name': 'Detroit Red Wings',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/DET_light.svg?season=20252026'},
 {'team_id': 17,
  'team_abbrev': 'CBJ',
  'team_name': 'Columbus Blue Jackets',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg'},
 {'team_id': 18,
  'team_abbrev': 'ANA',
  'team_name': 'Anaheim Ducks',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/ANA_light.svg'},
 {'team_id': 19,
  'team_abbrev': 'NYI',
  'team_name': 'New York Islanders',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NYI_light.svg'},
 {'team_id': 20,
  'team_abbrev': 'LAK',
  'team_name': 'Los Angeles Kings',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/LAK_light.svg'},
 {'team_id': 21,
  'team_abbrev': 'NJD',
  'team_name': 'New Jersey Devils',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NJD_light.svg'},
 {'team_id': 22,
  'team_abbrev': 'STL',
  'team_name': 'St. Louis Blues',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/STL_light.svg?season=20252026'},
 {'team_id': 23,
  'team_abbrev': 'NSH',
  'team_name': 'Nashville Predators',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NSH_light.svg'},
 {'team_id': 24,
  'team_abbrev': 'SJS',
  'team_name': 'San Jose Sharks',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/SJS_light.svg'},
 {'team_id': 25,
  'team_abbrev': 'FLA',
  'team_name': 'Florida Panthers',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/FLA_light.svg'},
 {'team_id': 26,
  'team_abbrev': 'WPG',
  'team_name': 'Winnipeg Jets',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/WPG_light.svg'},
 {'team_id': 27,
  'team_abbrev': 'SEA',
  'team_name': 'Seattle Kraken',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/SEA_light.svg'},
 {'team_id': 28,
  'team_abbrev': 'TOR',
  'team_name': 'Toronto Maple Leafs',
  'conference_name': 'Eastern',
  'division_name': 'Atlantic',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/TOR_light.svg'},
 {'team_id': 29,
  'team_abbrev': 'CGY',
  'team_name': 'Calgary Flames',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CGY_light.svg'},
 {'team_id': 30,
  'team_abbrev': 'NYR',
  'team_name': 'New York Rangers',
  'conference_name': 'Eastern',
  'division_name': 'Metropolitan',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NYR_light.svg'},
 {'team_id': 31,
  'team_abbrev': 'CHI',
  'team_name': 'Chicago Blackhawks',
  'conference_name': 'Western',
  'division_name': 'Central',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CHI_light.svg?season=20252026'},
 {'team_id': 32,
  'team_abbrev': 'VAN',
  'team_name': 'Vancouver Canucks',
  'conference_name': 'Western',
  'division_name': 'Pacific',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/VAN_light.svg'}]

In [3]:
import mysql.connector

connection = mysql.connector.connect(
    host='localhost',
    port=3306,
    database='NHL_ANALYTICS_PROJECT',
    user='root',
    password="Omsivaya@20"
)

In [21]:
if connection.is_connected():
        cursor = connection.cursor()

In [22]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /Users/nareshselvaraj/Documents/Claude Experiements/Pythonproject/.venv/lib/python3.12/site-packages (26.7.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [24]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS teams (
    team_id INT AUTO_INCREMENT PRIMARY KEY,
    team_abbrev VARCHAR(10) UNIQUE,
    team_name VARCHAR(100) NOT NULL,
    conference_name VARCHAR(100),
    division_name VARCHAR(100),
    logo_url TEXT
)
""")

connection.commit()
print('Teams table created successfully.')

Teams table created successfully.

In [31]:
insert_query = """
INSERT INTO teams (
    team_abbrev,
    team_name,
    conference_name,
    division_name,
    logo_url
)
VALUES (%s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    team_name = VALUES(team_name),
    conference_name = VALUES(conference_name),
    division_name = VALUES(division_name),
    logo_url = VALUES(logo_url)
"""

for i in records:
    team_values = (
        i['team_abbrev'],
        i['team_name'],
        i['conference_name'],
        i['division_name'],
        i['logo_url']
    )

    cursor.execute(insert_query, team_values)

connection.commit()
print(f"{len(records)} teams inserted or updated successfully.")

32 teams inserted or updated successfully.

In [35]:
import pandas as pd
df = pd.read_sql_query("select * from teams", connection)
df

/var/folders/f7/2dmww_657j51jk3c1xsbw30h0000gn/T/ipykernel_6132/2365296734.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("select * from teams", connection)

,team_id,team_abbrev,team_name,conference_name,division_name,logo_url
0,1,COL,Colorado Avalanche,Western,Central,https://assets.nhle.com/logos/nhl/svg/COL_ligh...
1,2,CAR,Carolina Hurricanes,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CAR_ligh...
2,3,DAL,Dallas Stars,Western,Central,https://assets.nhle.com/logos/nhl/svg/DAL_ligh...
3,4,BUF,Buffalo Sabres,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BUF_ligh...
4,5,TBL,Tampa Bay Lightning,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TBL_ligh...
5,6,MTL,Montréal Canadiens,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...
6,7,MIN,Minnesota Wild,Western,Central,https://assets.nhle.com/logos/nhl/svg/MIN_ligh...
7,8,BOS,Boston Bruins,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BOS_ligh...
8,9,OTT,Ottawa Senators,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/OTT_ligh...
9,10,PIT,Pittsburgh Penguins,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/PIT_ligh...
10,11,PHI,Philadelphia Flyers,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/PHI_ligh...
11,12,WSH,Washington Capitals,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/WSH_seco...
12,13,VGK,Vegas Golden Knights,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/VGK_ligh...
13,14,EDM,Edmonton Oilers,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/EDM_ligh...
14,15,UTA,Utah Mammoth,Western,Central,https://assets.nhle.com/logos/nhl/svg/UTA_ligh...
15,16,DET,Detroit Red Wings,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/DET_ligh...
16,17,CBJ,Columbus Blue Jackets,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CBJ_ligh...
17,18,ANA,Anaheim Ducks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/ANA_ligh...
18,19,NYI,New York Islanders,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NYI_ligh...
19,20,LAK,Los Angeles Kings,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/LAK_ligh...
20,21,NJD,New Jersey Devils,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NJD_ligh...
21,22,STL,St. Louis Blues,Western,Central,https://assets.nhle.com/logos/nhl/svg/STL_ligh...
22,23,NSH,Nashville Predators,Western,Central,https://assets.nhle.com/logos/nhl/svg/NSH_ligh...
23,24,SJS,San Jose Sharks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/SJS_ligh...
24,25,FLA,Florida Panthers,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/FLA_ligh...
25,26,WPG,Winnipeg Jets,Western,Central,https://assets.nhle.com/logos/nhl/svg/WPG_ligh...
26,27,SEA,Seattle Kraken,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/SEA_ligh...
27,28,TOR,Toronto Maple Leafs,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...
28,29,CGY,Calgary Flames,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/CGY_ligh...
29,30,NYR,New York Rangers,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NYR_ligh...
30,31,CHI,Chicago Blackhawks,Western,Central,https://assets.nhle.com/logos/nhl/svg/CHI_ligh...
31,32,VAN,Vancouver Canucks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/VAN_ligh...

In [ ]:
#Last 3 tables

df_games = pd.read_json()

In [36]:
# Push it into SQL
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.54-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.7 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/nareshselvaraj/Documents/Claude Experiements/Pythonproject/.venv/lib/python3.12/site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.0.54-cp312-cp312-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 9.0 MB/s eta 0:00:00a 0:00:01
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.54

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [37]:
pip install --upgrade pip

Requirement already satisfied: pip in /Users/nareshselvaraj/Documents/Claude Experiements/Pythonproject/.venv/lib/python3.12/site-packages (24.3.1)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 5.9 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
Successfully installed pip-26.2.1
Note: you may need to restart the kernel to use updated packages.

In [38]:
import pymysql

from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:Omsivaya@20@localhost/NHL_ANALYTICS_PROJECT')

In [39]:
df_games = pd.read_json('/Users/nareshselvaraj/pandas course/NHL Analytics Hub Guvi Project/game_stats.json')
df_games

,stat_id,game_id,player_id,team_id,goals,assists,points,shots_on_goal,penalty_min,toi,plus_minus
0,1,2025010051,8480448,1,0,0,0,0,0,14:28,0
1,2,2025010051,8479525,1,0,0,0,0,0,18:48,-1
2,3,2025010051,8477492,1,0,1,1,0,0,18:57,1
3,6,2025010051,8477476,1,1,1,2,0,0,20:44,2
4,10,2025010051,8482947,1,1,0,1,0,0,12:48,1
...,...,...,...,...,...,...,...,...,...,...,...
47403,53923,2025021300,8476879,20,0,0,0,0,0,18:25,-1
47404,53924,2025021300,8476441,20,0,0,0,0,0,18:48,0
47405,53925,2025021300,8474563,20,0,1,1,0,0,22:20,1
47406,53926,2025021300,8479998,20,0,0,0,0,0,19:50,2
47407,53927,2025021300,8482730,20,0,0,0,0,0,22:39,0

In [42]:
df_games.to_sql('game_stats',if_exists='replace', con=engine)

47408

In [44]:
import requests

standings_response = requests.get(
    "https://api-web.nhle.com/v1/standings/now",
    timeout=30
)
standings_response.raise_for_status()
standings_payload = standings_response.json()
standings_data = standings_payload['standings']

print(f"Standings records: {len(standings_data)}")
print(sorted(standings_data[0].keys()))
print([(team['teamAbbrev'], team['streakCode'], team['streakCount']) for team in standings_data[:5]])

Standings records: 32
['conferenceAbbrev', 'conferenceHomeSequence', 'conferenceL10Sequence', 'conferenceName', 'conferenceRoadSequence', 'conferenceSequence', 'date', 'divisionAbbrev', 'divisionHomeSequence', 'divisionL10Sequence', 'divisionName', 'divisionRoadSequence', 'divisionSequence', 'gameTypeId', 'gamesPlayed', 'goalAgainst', 'goalDifferential', 'goalDifferentialPctg', 'goalFor', 'goalsForPctg', 'homeGamesPlayed', 'homeGoalDifferential', 'homeGoalsAgainst', 'homeGoalsFor', 'homeLosses', 'homeOtLosses', 'homePoints', 'homeRegulationPlusOtWins', 'homeRegulationWins', 'homeTies', 'homeWins', 'l10GamesPlayed', 'l10GoalDifferential', 'l10GoalsAgainst', 'l10GoalsFor', 'l10Losses', 'l10OtLosses', 'l10Points', 'l10RegulationPlusOtWins', 'l10RegulationWins', 'l10Ties', 'l10Wins', 'leagueHomeSequence', 'leagueL10Sequence', 'leagueRoadSequence', 'leagueSequence', 'losses', 'otLosses', 'placeName', 'pointPctg', 'points', 'regulationPlusOtWinPctg', 'regulationPlusOtWins', 'regulationWinPctg', 'regulationWins', 'roadGamesPlayed', 'roadGoalDifferential', 'roadGoalsAgainst', 'roadGoalsFor', 'roadLosses', 'roadOtLosses', 'roadPoints', 'roadRegulationPlusOtWins', 'roadRegulationWins', 'roadTies', 'roadWins', 'seasonId', 'shootoutLosses', 'shootoutWins', 'streakCode', 'streakCount', 'teamAbbrev', 'teamCommonName', 'teamLogo', 'teamLogoDark', 'teamName', 'ties', 'waiversSequence', 'wildcardSequence', 'winPctg', 'wins']
[({'default': 'EDM'}, 'W', 1), ({'default': 'FLA'}, 'OT', 1), ({'default': 'PIT'}, 'W', 1), ({'default': 'UTA'}, 'W', 1), ({'default': 'SEA'}, 'W', 1)]

In [47]:
standings_cursor = connection.cursor()

standings_cursor.execute("""
CREATE TABLE IF NOT EXISTS standings (
    standing_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT NOT NULL,
    season VARCHAR(20) NOT NULL,
    games_played INT NOT NULL,
    wins INT NOT NULL,
    losses INT NOT NULL,
    ot_losses INT NOT NULL,
    points INT NOT NULL,
    goals_for INT NOT NULL,
    goals_against INT NOT NULL,
    home_wins INT NOT NULL,
    away_wins INT NOT NULL,
    streak_type VARCHAR(20),
    streak_count INT,
    UNIQUE KEY uq_standings_team_season (team_id, season),
    CONSTRAINT fk_standings_team
        FOREIGN KEY (team_id) REFERENCES teams(team_id)
) ENGINE=InnoDB
""")

standings_cursor.execute("SELECT team_id, team_abbrev FROM teams")
team_ids_by_abbrev = {
    team_abbrev: team_id
    for team_id, team_abbrev in standings_cursor.fetchall()
}

standings_records = []
missing_teams = []

for team in standings_data:
    abbrev_value = team['teamAbbrev']
    team_abbrev = abbrev_value['default'] if isinstance(abbrev_value, dict) else abbrev_value
    team_id = team_ids_by_abbrev.get(team_abbrev)

    if team_id is None:
        missing_teams.append(team_abbrev)
        continue

    standings_records.append((
        team_id,
        str(team['seasonId']),
        team['gamesPlayed'],
        team['wins'],
        team['losses'],
        team['otLosses'],
        team['points'],
        team['goalFor'],
        team['goalAgainst'],
        team['homeWins'],
        team['roadWins'],
        team.get('streakCode'),
        team.get('streakCount')
    ))

if missing_teams:
    raise ValueError(f"Teams missing from teams table: {missing_teams}")

upsert_standings_query = """
INSERT INTO standings (
    team_id, season, games_played, wins, losses, ot_losses, points,
    goals_for, goals_against, home_wins, away_wins, streak_type, streak_count
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    games_played = VALUES(games_played),
    wins = VALUES(wins),
    losses = VALUES(losses),
    ot_losses = VALUES(ot_losses),
    points = VALUES(points),
    goals_for = VALUES(goals_for),
    goals_against = VALUES(goals_against),
    home_wins = VALUES(home_wins),
    away_wins = VALUES(away_wins),
    streak_type = VALUES(streak_type),
    streak_count = VALUES(streak_count)
"""

standings_cursor.executemany(upsert_standings_query, standings_records)
connection.commit()

standings_cursor.execute("""
SELECT season, COUNT(*) AS team_count
FROM standings
GROUP BY season
ORDER BY season
""")
print(f"Loaded {len(standings_records)} standings rows.")
print(standings_cursor.fetchall())

Loaded 32 standings rows.
[('20262027', 32)]

In [49]:
standings_cursor

In [51]:
standings_cursor.execute("""
SELECT
    t.team_abbrev,
    t.team_name,
    s.season,
    s.games_played,
    s.wins,
    s.losses,
    s.ot_losses,
    s.points,
    s.goals_for,
    s.goals_against,
    s.home_wins,
    s.away_wins,
    s.streak_type,
    s.streak_count
FROM standings AS s
JOIN teams AS t ON t.team_id = s.team_id
ORDER BY s.points DESC, s.wins DESC
""")

standings_rows = standings_cursor.fetchall()
standings_df = pd.DataFrame(standings_rows, columns=[column[0] for column in standings_cursor.description])
standings_df

,team_abbrev,team_name,season,games_played,wins,losses,ot_losses,points,goals_for,goals_against,home_wins,away_wins,streak_type,streak_count
0,EDM,Edmonton Oilers,20262027,2,1,0,1,3,14,13,0,1,W,1.0
1,FLA,Florida Panthers,20262027,2,1,0,1,3,4,4,0,1,OT,1.0
2,PIT,Pittsburgh Penguins,20262027,1,1,0,0,2,7,0,0,1,W,1.0
3,UTA,Utah Mammoth,20262027,1,1,0,0,2,6,0,1,0,W,1.0
4,SEA,Seattle Kraken,20262027,1,1,0,0,2,6,1,0,1,W,1.0
5,COL,Colorado Avalanche,20262027,1,1,0,0,2,8,4,1,0,W,1.0
6,CBJ,Columbus Blue Jackets,20262027,1,1,0,0,2,6,3,1,0,W,1.0
7,VGK,Vegas Golden Knights,20262027,1,1,0,0,2,5,2,1,0,W,1.0
8,BOS,Boston Bruins,20262027,1,1,0,0,2,3,0,1,0,W,1.0
9,MIN,Minnesota Wild,20262027,1,1,0,0,2,3,1,0,1,W,1.0
10,MTL,Montréal Canadiens,20262027,1,1,0,0,2,3,2,0,1,W,1.0
11,SJS,San Jose Sharks,20262027,1,1,0,0,2,4,3,1,0,W,1.0
12,NJD,New Jersey Devils,20262027,1,1,0,0,2,3,2,1,0,W,1.0
13,NYR,New York Rangers,20262027,2,1,1,0,2,5,4,1,0,W,1.0
14,TOR,Toronto Maple Leafs,20262027,2,1,1,0,2,4,4,1,0,W,1.0
15,VAN,Vancouver Canucks,20262027,2,1,1,0,2,13,14,0,1,L,1.0
16,CAR,Carolina Hurricanes,20262027,1,0,0,1,1,0,1,0,0,OT,1.0
17,PHI,Philadelphia Flyers,20262027,2,0,1,1,1,2,10,0,0,OT,1.0
18,ANA,Anaheim Ducks,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
19,DAL,Dallas Stars,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
20,DET,Detroit Red Wings,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
21,OTT,Ottawa Senators,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
22,STL,St. Louis Blues,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
23,WSH,Washington Capitals,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
24,WPG,Winnipeg Jets,20262027,0,0,0,0,0,0,0,0,0,NaN,NaN
25,NYI,New York Islanders,20262027,1,0,1,0,0,1,2,0,0,L,1.0
26,NSH,Nashville Predators,20262027,1,0,1,0,0,1,3,0,0,L,1.0
27,BUF,Buffalo Sabres,20262027,1,0,1,0,0,3,6,0,0,L,1.0
28,LAK,Los Angeles Kings,20262027,1,0,1,0,0,4,8,0,0,L,1.0
29,TBL,Tampa Bay Lightning,20262027,1,0,1,0,0,1,5,0,0,L,1.0
30,CGY,Calgary Flames,20262027,1,0,1,0,0,1,6,0,0,L,1.0
31,CHI,Chicago Blackhawks,20262027,2,0,2,0,0,2,11,0,0,L,2.0

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed

players_cursor = connection.cursor()
players_cursor.execute("""
CREATE TABLE IF NOT EXISTS players (
    player_id BIGINT PRIMARY KEY,
    team_id INT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    position VARCHAR(10),
    jersey_number INT,
    birth_date DATE,
    birth_country VARCHAR(10),
    height_cm REAL,
    weight_kg REAL,
    shoots_catches VARCHAR(5),
    headshot_url TEXT,
    CONSTRAINT fk_players_team
        FOREIGN KEY (team_id) REFERENCES teams(team_id)
) ENGINE=InnoDB
""")

players_cursor.execute("SELECT team_id, team_abbrev FROM teams ORDER BY team_abbrev")
teams_for_rosters = players_cursor.fetchall()


def fetch_team_roster(team_id, team_abbrev):
    response = requests.get(
        f"https://api-web.nhle.com/v1/roster/{team_abbrev}/current",
        timeout=(5, 10)
    )
    response.raise_for_status()
    roster = response.json()
    position_map = {"L": "LW", "R": "RW"}
    team_records = []

    for group_name in ("forwards", "defensemen", "goalies"):
        for player in roster.get(group_name, []):
            first_name = player.get("firstName")
            last_name = player.get("lastName")
            position_code = player.get("positionCode")

            team_records.append((
                player["id"],
                team_id,
                first_name.get("default") if isinstance(first_name, dict) else first_name,
                last_name.get("default") if isinstance(last_name, dict) else last_name,
                position_map.get(position_code, position_code),
                player.get("sweaterNumber"),
                player.get("birthDate"),
                player.get("birthCountry"),
                player.get("heightInCentimeters"),
                player.get("weightInKilograms"),
                player.get("shootsCatches"),
                player.get("headshot")
            ))

    return team_abbrev, team_records


player_records = []
roster_errors = []

with ThreadPoolExecutor(max_workers=4) as executor:
    futures = {
        executor.submit(fetch_team_roster, team_id, team_abbrev): team_abbrev
        for team_id, team_abbrev in teams_for_rosters
    }

    for completed_count, future in enumerate(as_completed(futures), start=1):
        team_abbrev = futures[future]
        try:
            _, team_records = future.result()
            player_records.extend(team_records)
            print(f"Fetched {team_abbrev}: {len(team_records)} players ({completed_count}/{len(futures)} teams)")
        except requests.RequestException as error:
            roster_errors.append((team_abbrev, str(error)))
            print(f"Failed {team_abbrev} ({completed_count}/{len(futures)} teams): {error}")

if roster_errors:
    raise RuntimeError(
        f"Roster fetch failed for {len(roster_errors)} teams; no database rows were written. "
        f"Retry the cell after checking the network: {roster_errors}"
    )

upsert_players_query = """
INSERT INTO players (
    player_id, team_id, first_name, last_name, position, jersey_number,
    birth_date, birth_country, height_cm, weight_kg, shoots_catches, headshot_url
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    team_id = VALUES(team_id),
    first_name = VALUES(first_name),
    last_name = VALUES(last_name),
    position = VALUES(position),
    jersey_number = VALUES(jersey_number),
    birth_date = VALUES(birth_date),
    birth_country = VALUES(birth_country),
    height_cm = VALUES(height_cm),
    weight_kg = VALUES(weight_kg),
    shoots_catches = VALUES(shoots_catches),
    headshot_url = VALUES(headshot_url)
"""

players_cursor.executemany(upsert_players_query, player_records)
connection.commit()

players_cursor.execute("""
SELECT COUNT(*) AS player_count, COUNT(DISTINCT team_id) AS team_count
FROM players
""")
print(f"Fetched and saved {len(player_records)} player records.")
print("Database totals (players, teams):", players_cursor.fetchone())

In [2]:
import pandas as pd
df_players = pd.read_sql_query("SELECT * FROM players", connection)
df_players

NameError: name 'connection' is not defined

In [4]:
import mysql.connector
import pandas as pd

connection = mysql.connector.connect(
    host='localhost',
    port=3306,
    database='NHL_ANALYTICS_PROJECT',
    user='root',
    password="Omsivaya@20"
)

df_players = pd.read_sql_query("SELECT * FROM players", connection)
df_players

/var/folders/f7/2dmww_657j51jk3c1xsbw30h0000gn/T/ipykernel_16340/2531164442.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_players = pd.read_sql_query("SELECT * FROM players", connection)

,player_id,team_id,first_name,last_name,position,jersey_number,birth_date,birth_country,height_cm,weight_kg,shoots_catches,headshot_url
0,8470613,1,Brent,Burns,D,84.0,1985-03-09,CAN,196.0,103.0,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
1,8470621,20,Corey,Perry,RW,90.0,1985-05-16,CAN,191.0,95.0,R,https://assets.nhle.com/mugs/nhl/20262027/LAK/...
2,8471214,12,Alex,Ovechkin,LW,8.0,1985-09-17,RUS,191.0,108.0,R,https://assets.nhle.com/mugs/nhl/20262027/WSH/...
3,8471215,10,Evgeni,Malkin,C,71.0,1986-07-31,RUS,196.0,96.0,L,https://assets.nhle.com/mugs/nhl/20262027/PIT/...
4,8471675,10,Sidney,Crosby,C,87.0,1987-08-07,CAN,180.0,93.0,L,https://assets.nhle.com/mugs/nhl/20262027/PIT/...
...,...,...,...,...,...,...,...,...,...,...,...,...
767,8486072,18,Marcus,Nordmark,LW,43.0,2008-05-04,SWE,188.0,82.0,L,https://assets.nhle.com/mugs/nhl/20262027/ANA/...
768,8486103,24,Ivar,Stenberg,LW,41.0,2007-09-30,SWE,180.0,84.0,L,https://assets.nhle.com/mugs/nhl/20262027/SJS/...
769,8486161,14,Owen,Michaels,RW,43.0,2002-05-01,USA,185.0,83.0,R,https://assets.nhle.com/mugs/nhl/20262027/EDM/...
770,8486166,7,Viking,Gustafsson Nyberg,D,6.0,2003-09-21,SWE,198.0,102.0,L,https://assets.nhle.com/mugs/nhl/20262027/MIN/...
771,8486171,1,T.J.,Hughes,RW,13.0,2001-11-09,CAN,183.0,84.0,NaN,https://assets.nhle.com/mugs/nhl/20262027/COL/...

In [10]:
import json
import time
import requests

json_path = r"/Users/nareshselvaraj/pandas course/NHL Analytics Hub Guvi Project/skater_season_stats.json"

with open(json_path, "r") as json_file:
    skater_data = json.load(json_file)

skater_cursor = connection.cursor()
skater_cursor.execute("SELECT team_id, team_abbrev FROM teams")
team_rows = skater_cursor.fetchall()
db_team_ids = {team_id for team_id, _ in team_rows}
db_team_id_by_abbrev = {team_abbrev: team_id for team_id, team_abbrev in team_rows}

source_team_ids = {int(row["team_id"]) for row in skater_data}
unknown_team_ids = source_team_ids - db_team_ids
if unknown_team_ids:
    raise ValueError(f"JSON contains team IDs missing from teams table: {sorted(unknown_team_ids)}")

skater_cursor.execute("SELECT player_id, position FROM players")
player_positions = {
    int(player_id): position
    for player_id, position in skater_cursor.fetchall()
}

missing_player_ids = sorted({int(row["player_id"]) for row in skater_data} - set(player_positions))
source_team_by_player = {
    int(row["player_id"]): int(row["team_id"])
    for row in skater_data
}


def localized_value(value):
    return value.get("default") if isinstance(value, dict) else value


def fetch_player_details(player_id):
    url = f"https://api-web.nhle.com/v1/player/{player_id}/landing"

    for attempt in range(5):
        try:
            response = requests.get(url, timeout=(5, 15))
            if response.status_code == 429 or response.status_code >= 500:
                retry_after = response.headers.get("Retry-After")
                delay = float(retry_after) if retry_after else min(2 ** attempt, 30)
                print(f"NHL API busy for player {player_id}; retrying in {delay:g}s")
                time.sleep(delay)
                continue

            response.raise_for_status()
            player = response.json()
            abbrev = player.get("currentTeamAbbrev")
            team_id = db_team_id_by_abbrev.get(abbrev, source_team_by_player[player_id])

            return (
                player_id,
                team_id,
                localized_value(player.get("firstName")) or "Unknown",
                localized_value(player.get("lastName")) or "Unknown",
                localized_value(player.get("position")),
                player.get("sweaterNumber"),
                player.get("birthDate"),
                player.get("birthCountry"),
                player.get("heightInCentimeters"),
                player.get("weightInKilograms"),
                player.get("shootsCatches"),
                player.get("headshot")
            )
        except requests.RequestException:
            if attempt == 4:
                raise
            time.sleep(min(2 ** attempt, 30))

    raise RuntimeError(f"Could not fetch player {player_id} after retries")


supplemental_player_records = []
for player_number, player_id in enumerate(missing_player_ids, start=1):
    supplemental_player_records.append(fetch_player_details(player_id))
    if player_number % 10 == 0 or player_number == len(missing_player_ids):
        print(f"Fetched player details: {player_number}/{len(missing_player_ids)}")
    time.sleep(0.25)

skater_cursor.execute("""
CREATE TABLE IF NOT EXISTS skater_season_stats (
    stat_id INT AUTO_INCREMENT PRIMARY KEY,
    player_id BIGINT NOT NULL,
    season VARCHAR(20) NOT NULL,
    team_id INT NOT NULL,
    games_played INT,
    goals INT,
    assists INT,
    points INT,
    plus_minus INT,
    penalty_min INT,
    shots INT,
    avg_toi VARCHAR(10),
    UNIQUE KEY uq_skater_player_season_team (player_id, season, team_id),
    CONSTRAINT fk_skater_stats_player
        FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT fk_skater_stats_team
        FOREIGN KEY (team_id) REFERENCES teams(team_id)
) ENGINE=InnoDB
""")

upsert_player_query = """
INSERT INTO players (
    player_id, team_id, first_name, last_name, position, jersey_number,
    birth_date, birth_country, height_cm, weight_kg, shoots_catches, headshot_url
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    team_id = VALUES(team_id),
    first_name = VALUES(first_name),
    last_name = VALUES(last_name),
    position = VALUES(position),
    jersey_number = VALUES(jersey_number),
    birth_date = VALUES(birth_date),
    birth_country = VALUES(birth_country),
    height_cm = VALUES(height_cm),
    weight_kg = VALUES(weight_kg),
    shoots_catches = VALUES(shoots_catches),
    headshot_url = VALUES(headshot_url)
"""

upsert_skater_query = """
INSERT INTO skater_season_stats (
    player_id, season, team_id, games_played, goals, assists, points,
    plus_minus, penalty_min, shots, avg_toi
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    games_played = VALUES(games_played),
    goals = VALUES(goals),
    assists = VALUES(assists),
    points = VALUES(points),
    plus_minus = VALUES(plus_minus),
    penalty_min = VALUES(penalty_min),
    shots = VALUES(shots),
    avg_toi = VALUES(avg_toi)
"""

player_positions.update({record[0]: record[4] for record in supplemental_player_records})
skater_records = []
goalie_records = []
missing_players = []

for row in skater_data:
    player_id = int(row["player_id"])
    position = player_positions.get(player_id)

    if position is None:
        missing_players.append(player_id)
        continue
    if position == "G":
        goalie_records.append(row)
        continue

    skater_records.append((
        player_id,
        str(row["season"]),
        int(row["team_id"]),
        row.get("games_played"),
        row.get("goals"),
        row.get("assists"),
        row.get("points"),
        row.get("plus_minus"),
        row.get("penalty_min"),
        row.get("shots"),
        row.get("avg_toi")
    ))

if missing_players:
    raise ValueError(f"Could not determine positions for player IDs: {missing_players}")

try:
    if supplemental_player_records:
        skater_cursor.executemany(upsert_player_query, supplemental_player_records)
    if skater_records:
        skater_cursor.executemany(upsert_skater_query, skater_records)
    connection.commit()
except Exception:
    connection.rollback()
    raise

skater_cursor.execute("""
SELECT COUNT(*) AS stats_rows,
       COUNT(DISTINCT player_id) AS player_count,
       COUNT(DISTINCT team_id) AS team_count
FROM skater_season_stats
""")
print(f"Skater records inserted or updated: {len(skater_records)}")
print(f"Goalie records skipped for Table 7: {len(goalie_records)}")
print(f"Supplemental player records added: {len(supplemental_player_records)}")
print(f"avg_toi values present in JSON: {sum(row.get('avg_toi') is not None for row in skater_data)}")
print("Database totals (rows, players, teams):", skater_cursor.fetchone())
skater_cursor.close()

Fetched player details: 10/88
Fetched player details: 20/88
Fetched player details: 30/88
Fetched player details: 40/88
Fetched player details: 50/88
Fetched player details: 60/88
Fetched player details: 70/88
Fetched player details: 80/88
Fetched player details: 88/88
Skater records inserted or updated: 714
Goalie records skipped for Table 7: 0
Supplemental player records added: 88
avg_toi values present in JSON: 0
Database totals (rows, players, teams): (714, 714, 32)

True

In [11]:
df=pd.read_sql_query("SELECT * FROM skater_season_stats", connection)

/var/folders/f7/2dmww_657j51jk3c1xsbw30h0000gn/T/ipykernel_16340/3259520688.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM skater_season_stats", connection)

In [12]:
df

,stat_id,player_id,season,team_id,games_played,goals,assists,points,plus_minus,penalty_min,shots,avg_toi
0,1,8470613,20252026,1,82.0,12.0,23.0,35.0,33.0,32.0,172.0,None
1,2,8475172,20252026,1,77.0,16.0,34.0,50.0,-30.0,30.0,213.0,None
2,3,8475754,20252026,1,81.0,33.0,32.0,65.0,15.0,36.0,186.0,None
3,4,8475768,20252026,1,50.0,11.0,15.0,26.0,5.0,8.0,82.0,None
4,5,8476312,20252026,1,79.0,5.0,26.0,31.0,42.0,91.0,128.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,8483678,20252026,32,70.0,3.0,7.0,10.0,-16.0,39.0,46.0,None
710,711,8483768,20252026,32,24.0,0.0,3.0,3.0,-12.0,7.0,14.0,None
711,712,8484136,20252026,32,66.0,13.0,6.0,19.0,-13.0,26.0,62.0,None
712,713,8484240,20252026,32,70.0,5.0,16.0,21.0,-23.0,28.0,59.0,None
713,714,8484798,20252026,32,76.0,6.0,20.0,26.0,-33.0,41.0,73.0,None

In [13]:
df.head()

,stat_id,player_id,season,team_id,games_played,goals,assists,points,plus_minus,penalty_min,shots,avg_toi
0,1,8470613,20252026,1,82.0,12.0,23.0,35.0,33.0,32.0,172.0,None
1,2,8475172,20252026,1,77.0,16.0,34.0,50.0,-30.0,30.0,213.0,None
2,3,8475754,20252026,1,81.0,33.0,32.0,65.0,15.0,36.0,186.0,None
3,4,8475768,20252026,1,50.0,11.0,15.0,26.0,5.0,8.0,82.0,None
4,5,8476312,20252026,1,79.0,5.0,26.0,31.0,42.0,91.0,128.0,None

In [ ]:
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

SEASON = "20252026"

games_cursor = connection.cursor()
games_cursor.execute("""
CREATE TABLE IF NOT EXISTS games (
    game_id BIGINT PRIMARY KEY,
    season VARCHAR(20),
    game_type INT,
    game_date DATE,
    home_team_id INT NOT NULL,
    away_team_id INT NOT NULL,
    home_score INT,
    away_score INT,
    game_state VARCHAR(20),
    venue_name VARCHAR(150),
    CONSTRAINT fk_games_home_team
        FOREIGN KEY (home_team_id) REFERENCES teams(team_id),
    CONSTRAINT fk_games_away_team
        FOREIGN KEY (away_team_id) REFERENCES teams(team_id)
) ENGINE=InnoDB
""")

games_cursor.execute("SELECT team_id, team_abbrev FROM teams ORDER BY team_abbrev")
teams_for_schedule = games_cursor.fetchall()
team_id_by_abbrev = {team_abbrev: team_id for team_id, team_abbrev in teams_for_schedule}


def fetch_team_schedule(team_abbrev):
    max_attempts = 5
    for attempt in range(1, max_attempts + 1):
        response = requests.get(
            f"https://api-web.nhle.com/v1/club-schedule-season/{team_abbrev}/{SEASON}",
            timeout=(5, 10)
        )
        if response.status_code == 429 and attempt < max_attempts:
            time.sleep(2 ** attempt)
            continue
        response.raise_for_status()
        break
    payload = response.json()

    team_records = []
    for game in payload.get("games", []):
        home_abbrev = game["homeTeam"]["abbrev"]
        away_abbrev = game["awayTeam"]["abbrev"]
        home_team_id = team_id_by_abbrev.get(home_abbrev)
        away_team_id = team_id_by_abbrev.get(away_abbrev)
        if home_team_id is None or away_team_id is None:
            continue

        venue = game.get("venue")
        venue_name = venue.get("default") if isinstance(venue, dict) else venue

        team_records.append((
            game["id"],
            str(game.get("season")),
            game.get("gameType"),
            game.get("gameDate"),
            home_team_id,
            away_team_id,
            game["homeTeam"].get("score"),
            game["awayTeam"].get("score"),
            game.get("gameState"),
            venue_name,
        ))

    return team_abbrev, team_records


game_records_by_id = {}
schedule_errors = []

with ThreadPoolExecutor(max_workers=2) as executor:
    futures = {}
    for team_id, team_abbrev in teams_for_schedule:
        futures[executor.submit(fetch_team_schedule, team_abbrev)] = team_abbrev
        time.sleep(0.3)

    for completed_count, future in enumerate(as_completed(futures), start=1):
        team_abbrev = futures[future]
        try:
            _, team_records = future.result()
            for record in team_records:
                # dedupe in Python too: each game appears once from each side's schedule
                game_records_by_id[record[0]] = record
            print(f"Fetched {team_abbrev}: {len(team_records)} games ({completed_count}/{len(futures)} teams)")
        except requests.RequestException as error:
            schedule_errors.append((team_abbrev, str(error)))
            print(f"Failed {team_abbrev} ({completed_count}/{len(futures)} teams): {error}")

if schedule_errors:
    raise RuntimeError(
        f"Schedule fetch failed for {len(schedule_errors)} teams; no database rows were written. "
        f"Retry after checking the network: {schedule_errors}"
    )

insert_games_query = """
INSERT IGNORE INTO games (
    game_id, season, game_type, game_date, home_team_id, away_team_id,
    home_score, away_score, game_state, venue_name
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

game_records = list(game_records_by_id.values())
games_cursor.executemany(insert_games_query, game_records)
connection.commit()

games_cursor.execute("SELECT COUNT(*) FROM games")
print(f"Fetched {len(game_records)} unique games across {len(teams_for_schedule)} teams.")
print("Database total (games):", games_cursor.fetchone())